language: node_js
node_js:
  - '16'

before_install:
  - sudo apt-get update
  - sudo apt-get  -y install

before_deploy:
  - npm run build

jobs:
  include:
    - stage: Test
      script:
        - npm run test

    - stage: Version
      if: tag IS NOT present AND branch = master AND commit_message !~ /^Version /
      script:
        # Set up SSH key for GitHub
        - openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv -in .travis/github_deploy_key.enc -out github_deploy_key -d
        - chmod 600 github_deploy_key
        - eval $(ssh-agent -s)
        - ssh-add github_deploy_key
        # Patch for NPM
        - npm version patch -m "Version %s"
        # Set remote to SSH instead of HTTPS
        - git remote set-url origin git@github.com:trinhthinh388/fetch-interceptors.git
        # Push new tag to GitHub, triggering a new build
        - git push origin HEAD:master --follow-tags
      on:
        tags: false

    - stage: Release
      if: tag IS present AND commit_message =~ /^Version /
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
