language: node_js
node_js: - "16"
script:
  - npm run test
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  skip_cleanup: true
  on:
    branch: release
