name: Test

on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: yarn install
      - run: yarn test
